title: Min Lee
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description:
  <br>
  IT professional with over a decade of experience across diverse industries. Problem-solving expert and troubleshooter with SQL being instrumental in investigative work and identifying trends for problem resolution. Now seeking to transition into a Data-focused role.
  
  <br><br>
  Recent graduate of a Postgraduate Certificate degree from Auckland University of Technology, with the focus on Data Warehousing & Big Data, Business Analytics, Data Mining & Machine Learning and Artificial Intelligence.
  
  <br><br>
  <a href="https://www.linkedin.com/in/min-lee-4168723/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
